version: "2"

# create a drupal container with postgres db.

services:
  drupal:
    image: drupal
    ports:
      - "8080:8080"
    depends_on:
      - postgres-db
  postgres-db:
    image: postgres
    environment:
      POSTGRES_DB: postgres-db
      POSTGRES_USER: postgres-user
      POSTGRES_PASSWORD: postgres-secret-password
    volume:
      - postgresql_data:/var/lib/postgresql/data

volumes:
  postgresql_data:
